apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-secret-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"  # Deploy after external-secrets operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: blueberry
  source:
    repoURL: https://gitlab.com/obtain-blew/argocd-apps.git
    path: base/external-secrets
    targetRevision: main
    directory:
      include: 'gitlab-token-secret.yml'  # Only include the secret resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
