---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gsm-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  provider:
    gcpsm:
      projectID: development-454916
      auth:
        workloadIdentity:
          clusterLocation: us-east1
          clusterName: blueberry-dev-cluster
          serviceAccountRef:
            name: external-secrets-sa
