---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blueberry-root-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: blueberry
  source:
    repoURL: https://gitlab.com/obtain-blew/argocd-apps.git
    path: overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    # GKE Autopilot manages resources automatically
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/*/resources
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/spec/containers/*/resources
