---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-apps-repo-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  secretStoreRef:
    name: gsm-store
    kind: SecretStore
  target:
    name: argocd-apps-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: git
        url: https://gitlab.com/obtain-blew/argocd-apps.git
        username: "x-token-auth"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: gitlab-token
