---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-apps-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    # This secret will be managed by External Secrets Operator
    argocd.argoproj.io/sync-wave: "-10"
type: Opaque
stringData:
  type: git
  url: https://gitlab.com/obtain-blew/argocd-apps.git
  # Username and password will be populated by External Secrets
  username: PLACEHOLDER
  password: PLACEHOLDER