---
name: CI

'on':
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  KUSTOMIZE_VERSION: "5.2.1"
  KUBECONFORM_VERSION: "0.6.4"
  KUBE_SCORE_VERSION: "1.17.0"

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint -s .

  single-doc-check:
    name: Single Document Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for multi-document YAML files
        run: |
          set -eo pipefail
          failed=0
          for f in $(git ls-files '*.y*ml'); do
            if grep -qE '^---' "$f"; then
              echo "WARNING: $f contains multiple YAML documents" >&2
              failed=1
            fi
          done
          exit $failed

  kustomize-build-dev:
    name: Kustomize Build Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          # Install kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- ${KUSTOMIZE_VERSION}
          sudo mv kustomize /usr/local/bin/
          kustomize version

          # Install kubeconform
          wget -q https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/
          kubeconform -v

      - name: Build and validate dev overlay
        run: |
          SCHEMA_LOCATION='https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
          kustomize build overlays/dev | kubeconform -strict -summary -schema-location "${SCHEMA_LOCATION}" -schema-location default

  kustomize-build-prod:
    name: Kustomize Build Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          # Install kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- ${KUSTOMIZE_VERSION}
          sudo mv kustomize /usr/local/bin/
          kustomize version

          # Install kubeconform
          wget -q https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/
          kubeconform -v

      - name: Build and validate prod overlay
        run: |
          SCHEMA_LOCATION='https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
          kustomize build overlays/prod | kubeconform -strict -summary -schema-location "${SCHEMA_LOCATION}" -schema-location default

  kube-score:
    name: Kube Score
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          # Install kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- ${KUSTOMIZE_VERSION}
          sudo mv kustomize /usr/local/bin/
          kustomize version

          # Install kube-score
          wget -q https://github.com/zegl/kube-score/releases/download/v${KUBE_SCORE_VERSION}/kube-score_${KUBE_SCORE_VERSION}_linux_amd64.tar.gz
          tar xf kube-score_${KUBE_SCORE_VERSION}_linux_amd64.tar.gz
          sudo mv kube-score /usr/local/bin/
          kube-score version

      - name: Run kube-score
        run: |
          kustomize build overlays/dev > /tmp/dev.yaml
          kube-score score /tmp/dev.yaml --output-format ci

  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
